const fs = require('fs');
const path = require('path');

const baseDir = path.join(__dirname, 'backend', 'src');

const files = {
  'auth/auth.module.ts': `import { Module } from '@nestjs/common';\nimport { AuthController } from './auth.controller';\nimport { AuthService } from './auth.service';\nimport { JwtModule } from '@nestjs/jwt';\nimport { MongooseModule } from '@nestjs/mongoose';\nimport { User, UserSchema } from '../schemas/User.schema';\n\n@Module({\n  imports: [\n    MongooseModule.forFeature([{ name: User.name, schema: UserSchema }]),\n    JwtModule.register({ secret: process.env.JWT_SECRET || 'supersecret123', signOptions: { expiresIn: '1d' } })\n  ],\n  controllers: [AuthController],\n  providers: [AuthService]\n})\nexport class AuthModule {}`,
  
  'auth/auth.controller.ts': `import { Controller, Post, Body } from '@nestjs/common';\nimport { AuthService } from './auth.service';\n\n@Controller('auth')\nexport class AuthController {\n  constructor(private readonly authService: AuthService) {}\n\n  @Post('register')\n  register(@Body() body: any) {\n    return this.authService.register(body);\n  }\n\n  @Post('login')\n  login(@Body() body: any) {\n    return this.authService.login(body);\n  }\n}`,

  'auth/auth.service.ts': `import { Injectable, UnauthorizedException } from '@nestjs/common';\nimport { InjectModel } from '@nestjs/mongoose';\nimport { Model } from 'mongoose';\nimport { User, UserDocument } from '../schemas/User.schema';\nimport { JwtService } from '@nestjs/jwt';\nimport * as bcrypt from 'bcrypt';\n\n@Injectable()\nexport class AuthService {\n  constructor(\n    @InjectModel(User.name) private userModel: Model<UserDocument>,\n    private jwtService: JwtService\n  ) {}\n\n  async register(data: any) {\n    const hash = await bcrypt.hash(data.password, 10);\n    const user = new this.userModel({ ...data, passwordHash: hash });\n    await user.save();\n    return { token: this.jwtService.sign({ sub: user._id, role: user.role }) };\n  }\n\n  async login(data: any) {\n    const user = await this.userModel.findOne({ email: data.email });\n    if (!user || !(await bcrypt.compare(data.password, user.passwordHash))) {\n      throw new UnauthorizedException();\n    }\n    return { token: this.jwtService.sign({ sub: user._id, role: user.role }), user: { id: user._id, role: user.role, name: user.name } };\n  }\n}`,

  'orders/orders.module.ts': `import { Module } from '@nestjs/common';\nimport { OrdersController } from './orders.controller';\nimport { OrdersService } from './orders.service';\nimport { MongooseModule } from '@nestjs/mongoose';\nimport { Order, OrderSchema } from '../schemas/Order.schema';\nimport { User, UserSchema } from '../schemas/User.schema';\n\n@Module({\n  imports: [MongooseModule.forFeature([{ name: Order.name, schema: OrderSchema }, { name: User.name, schema: UserSchema }])],\n  controllers: [OrdersController],\n  providers: [OrdersService]\n})\nexport class OrdersModule {}`,

  'orders/orders.controller.ts': `import { Controller, Post, Get, Patch, Body, Param, Query } from '@nestjs/common';\nimport { OrdersService } from './orders.service';\n\n@Controller('orders')\nexport class OrdersController {\n  constructor(private readonly ordersService: OrdersService) {}\n\n  @Post()\n  createOrder(@Body() body: any) {\n    return this.ordersService.create(body);\n  }\n\n  @Get()\n  getAll(@Query() query: any) {\n    return this.ordersService.findAll(query);\n  }\n\n  @Get('my')\n  getMy(@Query('clientId') clientId: string) {\n    return this.ordersService.findByClient(clientId);\n  }\n\n  @Patch(':id/status')\n  updateStatus(@Param('id') id: string, @Body() body: any) {\n    return this.ordersService.updateStatus(id, body);\n  }\n}`,

  'orders/orders.service.ts': `import { Injectable, ServiceUnavailableException } from '@nestjs/common';\nimport { InjectModel } from '@nestjs/mongoose';\nimport { Model } from 'mongoose';\nimport { Order, OrderDocument } from '../schemas/Order.schema';\nimport { User, UserDocument } from '../schemas/User.schema';\n\n@Injectable()\nexport class OrdersService {\n  constructor(\n    @InjectModel(Order.name) private orderModel: Model<OrderDocument>,\n    @InjectModel(User.name) private userModel: Model<UserDocument>\n  ) {}\n\n  async create(data: any) {\n    const riders = await this.userModel.find({ role: 'rider', status: 'available' });\n    if (riders.length === 0) throw new ServiceUnavailableException({ message: 'No riders available', retryAfter: 60 });\n    \n    // Simple assignment\n    const assignedRider = data.priority === 'urgent' ? \n      riders.sort((a, b) => (a.activeOrders||0) - (b.activeOrders||0))[0] : \n      riders[0];\n\n    const order = new this.orderModel({ ...data, status: 'assigned', riderId: assignedRider._id });\n    await order.save();\n    \n    // Emit socket event placeholder\n    console.log('[SOCKET] order_assigned:', { orderId: order._id, riderName: assignedRider.name });\n    \n    return order;\n  }\n\n  async findAll(query: any) { return this.orderModel.find(query).populate('riderId', 'name status'); }\n  async findByClient(clientId: string) { return this.orderModel.find({ clientId }).sort({ createdAt: -1 }); }\n  \n  async updateStatus(id: string, data: any) {\n    const order = await this.orderModel.findById(id);\n    order.status = data.status;\n    if (data.status === 'delivered') order.deliveredAt = new Date();\n    await order.save();\n    console.log(\`[NOTIFY] Order \${id} updated to \${data.status}\`);\n    return order;\n  }\n}`,

  'riders/riders.module.ts': `import { Module } from '@nestjs/common';\nimport { RidersController } from './riders.controller';\nimport { RidersService } from './riders.service';\nimport { MongooseModule } from '@nestjs/mongoose';\nimport { User, UserSchema } from '../schemas/User.schema';\n\n@Module({\n  imports: [MongooseModule.forFeature([{ name: User.name, schema: UserSchema }])],\n  controllers: [RidersController],\n  providers: [RidersService]\n})\nexport class RidersModule {}`,

  'riders/riders.controller.ts': `import { Controller, Get, Patch, Param, Body } from '@nestjs/common';\nimport { RidersService } from './riders.service';\n\n@Controller('riders')\nexport class RidersController {\n  constructor(private readonly ridersService: RidersService) {}\n\n  @Get()\n  getAll() { return this.ridersService.findAll(); }\n\n  @Patch(':id/status')\n  updateStatus(@Param('id') id: string, @Body() body: any) { return this.ridersService.updateStatus(id, body.status); }\n\n  @Patch('location')\n  updateLocation(@Body() body: any) { return this.ridersService.updateLocation(body); }\n}`,

  'riders/riders.service.ts': `import { Injectable } from '@nestjs/common';\nimport { InjectModel } from '@nestjs/mongoose';\nimport { Model } from 'mongoose';\nimport { User, UserDocument } from '../schemas/User.schema';\n\n@Injectable()\nexport class RidersService {\n  constructor(@InjectModel(User.name) private userModel: Model<UserDocument>) {}\n\n  async findAll() { return this.userModel.find({ role: 'rider' }); }\n  \n  async updateStatus(id: string, status: string) {\n    const rider = await this.userModel.findByIdAndUpdate(id, { status }, { new: true });\n    return rider;\n  }\n\n  async updateLocation(data: any) {\n    // cache in redis in real app\n    console.log('[SOCKET] location_update:', data);\n    return { success: true };\n  }\n}`,

  'analytics/analytics.module.ts': `import { Module } from '@nestjs/common';\nimport { AnalyticsController } from './analytics.controller';\nimport { AnalyticsService } from './analytics.service';\nimport { MongooseModule } from '@nestjs/mongoose';\nimport { Order, OrderSchema } from '../schemas/Order.schema';\n\n@Module({\n  imports: [MongooseModule.forFeature([{ name: Order.name, schema: OrderSchema }])],\n  controllers: [AnalyticsController],\n  providers: [AnalyticsService]\n})\nexport class AnalyticsModule {}`,

  'analytics/analytics.controller.ts': `import { Controller, Get } from '@nestjs/common';\nimport { AnalyticsService } from './analytics.service';\n\n@Controller('analytics')\nexport class AnalyticsController {\n  constructor(private readonly analyticsService: AnalyticsService) {}\n\n  @Get('summary')\n  getSummary() { return this.analyticsService.getSummary(); }\n}`,

  'analytics/analytics.service.ts': `import { Injectable } from '@nestjs/common';\nimport { InjectModel } from '@nestjs/mongoose';\nimport { Model } from 'mongoose';\nimport { Order, OrderDocument } from '../schemas/Order.schema';\n\n@Injectable()\nexport class AnalyticsService {\n  constructor(@InjectModel(Order.name) private orderModel: Model<OrderDocument>) {}\n\n  async getSummary() {\n    const totalOrders = await this.orderModel.countDocuments();\n    const delivered = await this.orderModel.countDocuments({ status: 'delivered' });\n    return { totalOrders, delivered, pending: totalOrders - delivered, successRate: totalOrders ? (delivered/totalOrders)*100 : 0 };\n  }\n}`,

  'notifications/notifications.module.ts': `import { Module } from '@nestjs/common';\nimport { NotificationsService } from './notifications.service';\n\n@Module({\n  providers: [NotificationsService],\n  exports: [NotificationsService]\n})\nexport class NotificationsModule {}`,

  'notifications/notifications.service.ts': `import { Injectable } from '@nestjs/common';\n\n@Injectable()\nexport class NotificationsService {\n  log(message: string) {\n    console.log(\`[NOTIFY] \${message}\`);\n  }\n}`,

  'redis/redis.module.ts': `import { Module, Global } from '@nestjs/common';\n\n@Global()\n@Module({\n  providers: [{\n    provide: 'REDIS_CLIENT',\n    useFactory: () => {\n      // mock for now\n      return { get: () => null, set: () => null };\n    }\n  }],\n  exports: ['REDIS_CLIENT']\n})\nexport class RedisModule {}`
};

for (const [relativePath, content] of Object.entries(files)) {
  const fullPath = path.join(baseDir, relativePath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content);
}
console.log('Backend files generated successfully.');
